#!/usr/bin/perl

use Cwd;
use File::Basename;

$numArgs = $#ARGV + 1;

if ($numArgs != 2)
{
  die "usage: perl psf2coe.pl <input.psf> <output.coe>\n";
}

open INFILE, ,"<", $ARGV[0] or die $!;
binmode INFILE;

$n = read(INFILE, $magic, 4, 0);

if (unpack('H*', $magic) ne "72b54a86")
{
  die "Script only works with psf2 format\n";
}

read(INFILE, $version   , 4);
read(INFILE, $headersize, 4);
read(INFILE, $flags     , 4);
read(INFILE, $length    , 4);
read(INFILE, $charsize  , 4);
read(INFILE, $height    , 4);
read(INFILE, $width     , 4);

printf "version   : " .unpack('l*<',$version) ."\n";
printf "headersize: " .unpack('l*>',$headersize) ."\n";
printf "flags     : " .unpack('l*>',$flags) ."\n";
printf "length    : " .unpack('l*>',$length) ."\n";
printf "charsize  : " .unpack('l*>',$charsize) ."\n";
printf "height    : " .unpack('l*>',$height) ."\n";
printf "width     : " .unpack('l*>',$width) ."\n";

# Write COE file
open OUTFILE, ">", $ARGV[1] or die $!;

print OUTFILE "; DO NOT EDIT THIS FILE BY HAND\n";
print OUTFILE "; This file has been generated automaticaly by psf2coe utility \n";
print OUTFILE "; Original file: " . $ARGV[0] . "\n\n";
print OUTFILE "  memory_initialization_radix  = 16;\n";
print OUTFILE "  memory_initialization_vector =\n";

## there is exactly $length caracters in the file
## each character is $charsize bytes
$total = unpack('l*>',$length)*unpack('l*>',$charsize);
for (1..$total) 
{
  read(INFILE, $buffer, 1);
  print OUTFILE unpack('H*', $buffer) ."\n";
} 
print OUTFILE "; END";
printf "DONE."